name: wrf-terkep
channels:
  - conda-forge
dependencies:
  - python=3.10
  - wrf-python
  - cartopy
  - geopandas
  - netcdf4
  - streamlit
  - pip
  - pip:
    - imageio
    - requests
    - scipy
    - matplotlib
